[app_style]
background = "24273A"
text = "CAD3F5"

[sidebar_style]
border_radius = 10
txt_color = "CAD3F5"
bg_color = "24273A"
border_color = "CAD3F5"
border_width = 0
de_border_radius = 10
de_txt_color = "CAD3F5"
de_bg_color = "1E2030"
de_border_color = "CAD3F5"
de_border_width = 0

[body_style]
border_radius = 10
txt_color = "CAD3F5"
bg_color = "8AADF4"
border_color = "CAD3F5"
border_width = 0
de_border_radius = 10
de_txt_color = "CAD3F5"
de_bg_color = "1E2030"
de_border_color = "CAD3F5"
de_border_width = 0

[menu_style]
txt_color = "CAD3F5"
bg_color = "24273A"
border_width = 2
border_radius = 10
border_color = "CAD3F5"
sel_txt_color = "24273A"
sel_bg_color = "8AADF4"

[list_style]
txt_color = "CAD3F5"
bg_color = "24273A"
handle_color = "CAD3F5"
border_radius = 10
border_width = 2
border_color = "CAD3F5"
