theme = "dark"
border = "pixel"
width = 5
primary = "super"
secondary = "shift"
exith = "both"
exitk = "e"
launchh = "pri"
launchk = "tab"
killh = "both"
killk = "c"
minih = "both"
minik = "z"
scratchh = "pri"
scratchk = "z"
